version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    overwrite: true   # Enable overwrite feature
hooks:
  BeforeInstall:
    - location: scripts/clear_cache.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/awscloudagent.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_nginx.sh
      timeout: 300
      runas: root
